In [1]:
from nltk.tag import CRFTagger
import pycrfsuite

In [37]:
try:
    import pycrfsuite
except ImportError:
    pass

In [38]:
ct = CRFTagger()
ct.set_model_file('all_indo_man_tag_corpus_model.crf.tagger')
hasil = ct.tag_sents([[u'Jenis', u'monyet', u'yang', u'dikerahkan', u'pemkot', u'berbadan', u'besar', u',', u'berekor', u'panjang']])
print hasil

[[(u'Jenis', 'NN'), (u'monyet', 'NN'), (u'yang', 'SC'), (u'dikerahkan', 'VB'), (u'pemkot', 'VB'), (u'berbadan', 'NN'), (u'besar', 'JJ'), (u',', 'Z'), (u'berekor', 'NN'), (u'panjang', 'JJ')]]

In [3]:
import pandas as pd

In [51]:
test = pd.read_csv('test-data.tsv', sep='\t')

In [52]:
test.head()

         kata  tag
0       Jenis  NaN
1      monyet  NaN
2        yang  NaN
3  dikerahkan  NaN
4      pemkot  NaN

In [53]:
list_kata = list(test['kata'])

In [54]:
list_kata_uni = [unicode(x) for x in list_kata]

In [55]:
testing = ct.tag_sents([list_kata_uni])
print testing

[[(u'Jenis', 'NN'), (u'monyet', 'NN'), (u'yang', 'SC'), (u'dikerahkan', 'VB'), (u'pemkot', 'VB'), (u'berbadan', 'NN'), (u'besar', 'JJ'), (u',', 'Z'), (u'berekor', 'NN'), (u'panjang', 'JJ'), (u',', 'Z'), (u'dan', 'CC'), (u'memiliki', 'VB'), (u'wajah', 'NN'), (u'berwarna', 'NN'), (u'hitam', 'JJ'), (u'.', 'Z'), (u'Kedua', 'CD'), (u'orang', 'NN'), (u'terkaya', 'NN'), (u'dunia', 'NN'), (u'itu', 'PR'), (u'sudah', 'MD'), (u'berhasil', 'VB'), (u'membujuk', 'VB'), (u'banyak', 'CD'), (u'orang', 'NN'), (u'yang', 'SC'), (u'sangat', 'RB'), (u'kaya', 'JJ'), (u'di', 'IN'), (u'Amerika', 'NNP'), (u'agar', 'SC'), (u'menyumbangkan', 'VB'), (u'separuh', 'CD'), (u'kekayaan', 'NN'), (u'mereka', 'PRP'), (u'.', 'Z'), (u'Hanya', 'RB'), (u'butuh', 'VB'), (u'enam', 'CD'), (u'tahun', 'NN'), (u'bagi', 'IN'), (u'Zuckerberg', 'NNP'), (u'untuk', 'SC'), (u'bisa', 'MD'), (u'mencapai', 'VB'), (u'kesuksesan', 'NN'), (u'seperti', 'IN'), (u'sekarang', 'NN'), (u'ini', 'PR'), (u',', 'Z'), (u'setelah', 'SC'), (u'sebelum', 'SC'), (u'-nya', 'PRP'), (u'dia', 'PRP'), (u'meluncurkan', 'VB'), (u'situs', 'NN'), (u'ini', 'PR'), (u'saat', 'NN'), (u'masih', 'MD'), (u'duduk', 'VB'), (u'sebagai', 'IN'), (u'mahasiswa', 'NN'), (u'di', 'IN'), (u'Universitas', 'NNP'), (u'Harvard', 'NNP'), (u'.', 'Z'), (u'Jamrud', 'NNP'), (u'itu', 'PR'), (u'akhirnya', 'RB'), (u'sampai', 'SC'), (u'ke', 'IN'), (u'Amerika', 'NNP'), (u',', 'Z'), (u'meskipun', 'SC'), (u'setibanya', 'RB'), (u'di', 'IN'), (u'Amerika', 'NNP'), (u'tidak', 'NEG'), (u'jelas', 'JJ'), (u'siapa', 'WH'), (u'pemilik', 'NN'), (u'-nya', 'PRP'), (u'.', 'Z'), (u'Sejumlah', 'NNP'), (u'surat kabar', 'NNP'), (u'Brasil', 'NNP'), (u'melaporkan', 'VB'), (u'Tiririca', 'NNP'), (u'-', 'Z'), (u'sama', 'JJ'), (u'seperti', 'IN'), (u'satu', 'CD'), (u'dari', 'IN'), (u'sepuluh', 'CD'), (u'warga', 'NN'), (u'Brasil', 'NNP'), (u'buta aksara', 'NNP'), (u'.', 'Z'), (u'Universitas', 'NNP'), (u'Indonesia ', 'NNP'), (u'adalah ', 'NNP'), (u'kampus ', 'NNP'), (u'modern', 'JJ'), (u',', 'Z'), (u'komprehensif', 'JJ'), (u',', 'Z'), (u'terbuka', 'VB'), (u',', 'Z'), (u'multibudaya', 'NN'), (u',', 'Z'), (u'dan', 'CC'), (u'humanis', 'NN'), (u'yang', 'SC'), (u'mencakup', 'VB'), (u'disiplin', 'NN'), (u'ilmu', 'NN'), (u'yang', 'SC'), (u'luas', 'JJ'), (u'.', 'Z'), (u'Di', 'NNP'), (u'Korea', 'NNP'), (u'Selatan', 'NNP'), (u',', 'Z'), (u'Wings', 'NNP'), (u'menjadi', 'VB'), (u'album', 'NN'), (u'terlaris', 'NN'), (u'di', 'IN'), (u'sejarah', 'NN'), (u'Gaon', 'NNP'), (u'Album', 'NNP'), (u'Chart', 'NNP'), (u'pada', 'IN'), (u'waktu', 'NN'), (u'itu', 'PR'), (u'.', 'Z'), (u'Google', 'NNP'), (u'didirikan', 'VB'), (u'oleh', 'IN'), (u'Larry', 'NNP'), (u'Page', 'NNP'), (u'dan', 'CC'), (u'Sergey', 'NNP'), (u'Brin', 'NNP'), (u'saat', 'NN'), (u'masih', 'MD'), (u'mahasiswa', 'VB'), (u'Ph.D.', 'NNP'), (u'di', 'IN'), (u'Universitas', 'NNP'), (u'Stanford', 'NNP'), (u'.', 'Z')]]

In [56]:
list_tag = [k[1] for k in testing[0]]

In [57]:
list_tag

['NN',
 'NN',
 'SC',
 'VB',
 'VB',
 'NN',
 'JJ',
 'Z',
 'NN',
 'JJ',
 'Z',
 'CC',
 'VB',
 'NN',
 'NN',
 'JJ',
 'Z',
 'CD',
 'NN',
 'NN',
 'NN',
 'PR',
 'MD',
 'VB',
 'VB',
 'CD',
 'NN',
 'SC',
 'RB',
 'JJ',
 'IN',
 'NNP',
 'SC',
 'VB',
 'CD',
 'NN',
 'PRP',
 'Z',
 'RB',
 'VB',
 'CD',
 'NN',
 'IN',
 'NNP',
 'SC',
 'MD',
 'VB',
 'NN',
 'IN',
 'NN',
 'PR',
 'Z',
 'SC',
 'SC',
 'PRP',
 'PRP',
 'VB',
 'NN',
 'PR',
 'NN',
 'MD',
 'VB',
 'IN',
 'NN',
 'IN',
 'NNP',
 'NNP',
 'Z',
 'NNP',
 'PR',
 'RB',
 'SC',
 'IN',
 'NNP',
 'Z',
 'SC',
 'RB',
 'IN',
 'NNP',
 'NEG',
 'JJ',
 'WH',
 'NN',
 'PRP',
 'Z',
 'NNP',
 'NNP',
 'NNP',
 'VB',
 'NNP',
 'Z',
 'JJ',
 'IN',
 'CD',
 'IN',
 'CD',
 'NN',
 'NNP',
 'NNP',
 'Z',
 'NNP',
 'NNP',
 'NNP',
 'NNP',
 'JJ',
 'Z',
 'JJ',
 'Z',
 'VB',
 'Z',
 'NN',
 'Z',
 'CC',
 'NN',
 'SC',
 'VB',
 'NN',
 'NN',
 'SC',
 'JJ',
 'Z',
 'NNP',
 'NNP',
 'NNP',
 'Z',
 'NNP',
 'VB',
 'NN',
 'NN',
 'IN',
 'NN',
 'NNP',
 'NNP',
 'NNP',
 'IN',
 'NN',
 'PR',
 'Z',
 'NNP',
 'VB',
 'IN',
 'NNP',
 'NNP',
 'CC',
 'NNP',
 'NNP',
 'NN',
 'MD',
 'VB',
 'NNP',
 'IN',
 'NNP',
 'NNP',
 'Z']

In [58]:
test['tag'] = list_tag

In [62]:
test

            kata  tag
0          Jenis   NN
1         monyet   NN
2           yang   SC
3     dikerahkan   VB
4         pemkot   VB
5       berbadan   NN
6          besar   JJ
7              ,    Z
8        berekor   NN
9        panjang   JJ
10             ,    Z
11           dan   CC
12      memiliki   VB
13         wajah   NN
14      berwarna   NN
15         hitam   JJ
16             .    Z
17         Kedua   CD
18         orang   NN
19       terkaya   NN
20         dunia   NN
21           itu   PR
22         sudah   MD
23      berhasil   VB
24      membujuk   VB
25        banyak   CD
26         orang   NN
27          yang   SC
28        sangat   RB
29          kaya   JJ
..           ...  ...
124            ,    Z
125        Wings  NNP
126      menjadi   VB
127        album   NN
128     terlaris   NN
129           di   IN
130      sejarah   NN
131         Gaon  NNP
132        Album  NNP
133        Chart  NNP
134         pada   IN
135        waktu   NN
136          itu   PR
137            .    Z
138       Google  NNP
139    didirikan   VB
140         oleh   IN
141        Larry  NNP
142         Page  NNP
143          dan   CC
144       Sergey  NNP
145         Brin  NNP
146         saat   NN
147        masih   MD
148    mahasiswa   VB
149        Ph.D.  NNP
150           di   IN
151  Universitas  NNP
152     Stanford  NNP
153            .    Z

[154 rows x 2 columns]

In [61]:
test.to_csv('list_tag_test.csv', index=False)

In [78]:
with open('hmmscratch/data/test_plus.txt') as f:
    plus = []
    for word in f.readlines():
        plus.append(word)

In [81]:
plus

['Berhubung monyet adalah satwa dilindungi di India, para penjaga di Taj Mahal membuat penanganan agar tidak mengganggu pengunjung.\n',
 'Salah satunya adalah menakut-nakutinya dengan ketapel.\n',
 'Tak cuma di Taj Mahal, kawanan monyet juga mulai agresif di New Delhi.']

In [82]:
list_of_str = [kata.split() for kata in plus]

In [83]:
list_of_str

[['Berhubung',
  'monyet',
  'adalah',
  'satwa',
  'dilindungi',
  'di',
  'India,',
  'para',
  'penjaga',
  'di',
  'Taj',
  'Mahal',
  'membuat',
  'penanganan',
  'agar',
  'tidak',
  'mengganggu',
  'pengunjung.'],
 ['Salah', 'satunya', 'adalah', 'menakut-nakutinya', 'dengan', 'ketapel.'],
 ['Tak',
  'cuma',
  'di',
  'Taj',
  'Mahal,',
  'kawanan',
  'monyet',
  'juga',
  'mulai',
  'agresif',
  'di',
  'New',
  'Delhi.']]

In [85]:
list_kata = []
for i in list_of_str:
    for j in i:
        list_kata.append(j)

In [86]:
list_kata

['Berhubung',
 'monyet',
 'adalah',
 'satwa',
 'dilindungi',
 'di',
 'India,',
 'para',
 'penjaga',
 'di',
 'Taj',
 'Mahal',
 'membuat',
 'penanganan',
 'agar',
 'tidak',
 'mengganggu',
 'pengunjung.',
 'Salah',
 'satunya',
 'adalah',
 'menakut-nakutinya',
 'dengan',
 'ketapel.',
 'Tak',
 'cuma',
 'di',
 'Taj',
 'Mahal,',
 'kawanan',
 'monyet',
 'juga',
 'mulai',
 'agresif',
 'di',
 'New',
 'Delhi.']

In [90]:
long_string = ' '.join(list_kata)

In [92]:
import re
fix_list = re.findall(r"[\w']+|[.,!?;]", long_string)

In [93]:
fix_list

['Berhubung',
 'monyet',
 'adalah',
 'satwa',
 'dilindungi',
 'di',
 'India',
 ',',
 'para',
 'penjaga',
 'di',
 'Taj',
 'Mahal',
 'membuat',
 'penanganan',
 'agar',
 'tidak',
 'mengganggu',
 'pengunjung',
 '.',
 'Salah',
 'satunya',
 'adalah',
 'menakut',
 'nakutinya',
 'dengan',
 'ketapel',
 '.',
 'Tak',
 'cuma',
 'di',
 'Taj',
 'Mahal',
 ',',
 'kawanan',
 'monyet',
 'juga',
 'mulai',
 'agresif',
 'di',
 'New',
 'Delhi',
 '.']

In [108]:
list_test_kata = list(test['kata'])

In [109]:
new_test_data = list_test_kata + fix_list

In [110]:
new_test_data

['Jenis',
 'monyet',
 'yang',
 'dikerahkan',
 'pemkot',
 'berbadan',
 'besar',
 ',',
 'berekor',
 'panjang',
 ',',
 'dan',
 'memiliki',
 'wajah',
 'berwarna',
 'hitam',
 '.',
 'Kedua',
 'orang',
 'terkaya',
 'dunia',
 'itu',
 'sudah',
 'berhasil',
 'membujuk',
 'banyak',
 'orang',
 'yang',
 'sangat',
 'kaya',
 'di',
 'Amerika',
 'agar',
 'menyumbangkan',
 'separuh',
 'kekayaan',
 'mereka',
 '.',
 'Hanya',
 'butuh',
 'enam',
 'tahun',
 'bagi',
 'Zuckerberg',
 'untuk',
 'bisa',
 'mencapai',
 'kesuksesan',
 'seperti',
 'sekarang',
 'ini',
 ',',
 'setelah',
 'sebelum',
 '-nya',
 'dia',
 'meluncurkan',
 'situs',
 'ini',
 'saat',
 'masih',
 'duduk',
 'sebagai',
 'mahasiswa',
 'di',
 'Universitas',
 'Harvard',
 '.',
 'Jamrud',
 'itu',
 'akhirnya',
 'sampai',
 'ke',
 'Amerika',
 ',',
 'meskipun',
 'setibanya',
 'di',
 'Amerika',
 'tidak',
 'jelas',
 'siapa',
 'pemilik',
 '-nya',
 '.',
 'Sejumlah',
 'surat kabar',
 'Brasil',
 'melaporkan',
 'Tiririca',
 '-',
 'sama',
 'seperti',
 'satu',
 'dari',
 'sepuluh',
 'warga',
 'Brasil',
 'buta aksara',
 '.',
 'Universitas',
 'Indonesia ',
 'adalah ',
 'kampus ',
 'modern',
 ',',
 'komprehensif',
 ',',
 'terbuka',
 ',',
 'multibudaya',
 ',',
 'dan',
 'humanis',
 'yang',
 'mencakup',
 'disiplin',
 'ilmu',
 'yang',
 'luas',
 '.',
 'Di',
 'Korea',
 'Selatan',
 ',',
 'Wings',
 'menjadi',
 'album',
 'terlaris',
 'di',
 'sejarah',
 'Gaon',
 'Album',
 'Chart',
 'pada',
 'waktu',
 'itu',
 '.',
 'Google',
 'didirikan',
 'oleh',
 'Larry',
 'Page',
 'dan',
 'Sergey',
 'Brin',
 'saat',
 'masih',
 'mahasiswa',
 'Ph.D.',
 'di',
 'Universitas',
 'Stanford',
 '.',
 'Berhubung',
 'monyet',
 'adalah',
 'satwa',
 'dilindungi',
 'di',
 'India',
 ',',
 'para',
 'penjaga',
 'di',
 'Taj',
 'Mahal',
 'membuat',
 'penanganan',
 'agar',
 'tidak',
 'mengganggu',
 'pengunjung',
 '.',
 'Salah',
 'satunya',
 'adalah',
 'menakut',
 'nakutinya',
 'dengan',
 'ketapel',
 '.',
 'Tak',
 'cuma',
 'di',
 'Taj',
 'Mahal',
 ',',
 'kawanan',
 'monyet',
 'juga',
 'mulai',
 'agresif',
 'di',
 'New',
 'Delhi',
 '.']

In [112]:
new_test_data_uni = [unicode(x) for x in new_test_data]

In [113]:
new_testing = ct.tag_sents([new_test_data_uni])
print new_testing

[[(u'Jenis', 'NN'), (u'monyet', 'NN'), (u'yang', 'SC'), (u'dikerahkan', 'VB'), (u'pemkot', 'VB'), (u'berbadan', 'NN'), (u'besar', 'JJ'), (u',', 'Z'), (u'berekor', 'NN'), (u'panjang', 'JJ'), (u',', 'Z'), (u'dan', 'CC'), (u'memiliki', 'VB'), (u'wajah', 'NN'), (u'berwarna', 'NN'), (u'hitam', 'JJ'), (u'.', 'Z'), (u'Kedua', 'CD'), (u'orang', 'NN'), (u'terkaya', 'NN'), (u'dunia', 'NN'), (u'itu', 'PR'), (u'sudah', 'MD'), (u'berhasil', 'VB'), (u'membujuk', 'VB'), (u'banyak', 'CD'), (u'orang', 'NN'), (u'yang', 'SC'), (u'sangat', 'RB'), (u'kaya', 'JJ'), (u'di', 'IN'), (u'Amerika', 'NNP'), (u'agar', 'SC'), (u'menyumbangkan', 'VB'), (u'separuh', 'CD'), (u'kekayaan', 'NN'), (u'mereka', 'PRP'), (u'.', 'Z'), (u'Hanya', 'RB'), (u'butuh', 'VB'), (u'enam', 'CD'), (u'tahun', 'NN'), (u'bagi', 'IN'), (u'Zuckerberg', 'NNP'), (u'untuk', 'SC'), (u'bisa', 'MD'), (u'mencapai', 'VB'), (u'kesuksesan', 'NN'), (u'seperti', 'IN'), (u'sekarang', 'NN'), (u'ini', 'PR'), (u',', 'Z'), (u'setelah', 'SC'), (u'sebelum', 'SC'), (u'-nya', 'PRP'), (u'dia', 'PRP'), (u'meluncurkan', 'VB'), (u'situs', 'NN'), (u'ini', 'PR'), (u'saat', 'NN'), (u'masih', 'MD'), (u'duduk', 'VB'), (u'sebagai', 'IN'), (u'mahasiswa', 'NN'), (u'di', 'IN'), (u'Universitas', 'NNP'), (u'Harvard', 'NNP'), (u'.', 'Z'), (u'Jamrud', 'NNP'), (u'itu', 'PR'), (u'akhirnya', 'RB'), (u'sampai', 'SC'), (u'ke', 'IN'), (u'Amerika', 'NNP'), (u',', 'Z'), (u'meskipun', 'SC'), (u'setibanya', 'RB'), (u'di', 'IN'), (u'Amerika', 'NNP'), (u'tidak', 'NEG'), (u'jelas', 'JJ'), (u'siapa', 'WH'), (u'pemilik', 'NN'), (u'-nya', 'PRP'), (u'.', 'Z'), (u'Sejumlah', 'NNP'), (u'surat kabar', 'NNP'), (u'Brasil', 'NNP'), (u'melaporkan', 'VB'), (u'Tiririca', 'NNP'), (u'-', 'Z'), (u'sama', 'JJ'), (u'seperti', 'IN'), (u'satu', 'CD'), (u'dari', 'IN'), (u'sepuluh', 'CD'), (u'warga', 'NN'), (u'Brasil', 'NNP'), (u'buta aksara', 'NNP'), (u'.', 'Z'), (u'Universitas', 'NNP'), (u'Indonesia ', 'NNP'), (u'adalah ', 'NNP'), (u'kampus ', 'NNP'), (u'modern', 'JJ'), (u',', 'Z'), (u'komprehensif', 'JJ'), (u',', 'Z'), (u'terbuka', 'VB'), (u',', 'Z'), (u'multibudaya', 'NN'), (u',', 'Z'), (u'dan', 'CC'), (u'humanis', 'NN'), (u'yang', 'SC'), (u'mencakup', 'VB'), (u'disiplin', 'NN'), (u'ilmu', 'NN'), (u'yang', 'SC'), (u'luas', 'JJ'), (u'.', 'Z'), (u'Di', 'NNP'), (u'Korea', 'NNP'), (u'Selatan', 'NNP'), (u',', 'Z'), (u'Wings', 'NNP'), (u'menjadi', 'VB'), (u'album', 'NN'), (u'terlaris', 'NN'), (u'di', 'IN'), (u'sejarah', 'NN'), (u'Gaon', 'NNP'), (u'Album', 'NNP'), (u'Chart', 'NNP'), (u'pada', 'IN'), (u'waktu', 'NN'), (u'itu', 'PR'), (u'.', 'Z'), (u'Google', 'NNP'), (u'didirikan', 'VB'), (u'oleh', 'IN'), (u'Larry', 'NNP'), (u'Page', 'NNP'), (u'dan', 'CC'), (u'Sergey', 'NNP'), (u'Brin', 'NNP'), (u'saat', 'NN'), (u'masih', 'MD'), (u'mahasiswa', 'VB'), (u'Ph.D.', 'NNP'), (u'di', 'IN'), (u'Universitas', 'NNP'), (u'Stanford', 'NNP'), (u'.', 'Z'), (u'Berhubung', 'NNP'), (u'monyet', 'NN'), (u'adalah', 'VB'), (u'satwa', 'NN'), (u'dilindungi', 'VB'), (u'di', 'IN'), (u'India', 'NNP'), (u',', 'Z'), (u'para', 'DT'), (u'penjaga', 'NN'), (u'di', 'IN'), (u'Taj', 'NNP'), (u'Mahal', 'NNP'), (u'membuat', 'VB'), (u'penanganan', 'NN'), (u'agar', 'SC'), (u'tidak', 'NEG'), (u'mengganggu', 'VB'), (u'pengunjung', 'NN'), (u'.', 'Z'), (u'Salah', 'NNP'), (u'satunya', 'RB'), (u'adalah', 'VB'), (u'menakut', 'NN'), (u'nakutinya', 'RB'), (u'dengan', 'IN'), (u'ketapel', 'NN'), (u'.', 'Z'), (u'Tak', 'NEG'), (u'cuma', 'VB'), (u'di', 'IN'), (u'Taj', 'NNP'), (u'Mahal', 'NNP'), (u',', 'Z'), (u'kawanan', 'NN'), (u'monyet', 'NN'), (u'juga', 'RB'), (u'mulai', 'VB'), (u'agresif', 'JJ'), (u'di', 'IN'), (u'New', 'NNP'), (u'Delhi', 'NNP'), (u'.', 'Z')]]

In [105]:
with open('new_str.txt','w') as f:
    for kata in fix_list:
        f.write(kata + '\n')
f.close()

In [106]:
test

            kata  tag
0          Jenis   NN
1         monyet   NN
2           yang   SC
3     dikerahkan   VB
4         pemkot   VB
5       berbadan   NN
6          besar   JJ
7              ,    Z
8        berekor   NN
9        panjang   JJ
10             ,    Z
11           dan   CC
12      memiliki   VB
13         wajah   NN
14      berwarna   NN
15         hitam   JJ
16             .    Z
17         Kedua   CD
18         orang   NN
19       terkaya   NN
20         dunia   NN
21           itu   PR
22         sudah   MD
23      berhasil   VB
24      membujuk   VB
25        banyak   CD
26         orang   NN
27          yang   SC
28        sangat   RB
29          kaya   JJ
..           ...  ...
124            ,    Z
125        Wings  NNP
126      menjadi   VB
127        album   NN
128     terlaris   NN
129           di   IN
130      sejarah   NN
131         Gaon  NNP
132        Album  NNP
133        Chart  NNP
134         pada   IN
135        waktu   NN
136          itu   PR
137            .    Z
138       Google  NNP
139    didirikan   VB
140         oleh   IN
141        Larry  NNP
142         Page  NNP
143          dan   CC
144       Sergey  NNP
145         Brin  NNP
146         saat   NN
147        masih   MD
148    mahasiswa   VB
149        Ph.D.  NNP
150           di   IN
151  Universitas  NNP
152     Stanford  NNP
153            .    Z

[154 rows x 2 columns]

In [114]:
list_new_tag = [k[1] for k in new_testing[0]]

In [115]:
list_new_tag

['NN',
 'NN',
 'SC',
 'VB',
 'VB',
 'NN',
 'JJ',
 'Z',
 'NN',
 'JJ',
 'Z',
 'CC',
 'VB',
 'NN',
 'NN',
 'JJ',
 'Z',
 'CD',
 'NN',
 'NN',
 'NN',
 'PR',
 'MD',
 'VB',
 'VB',
 'CD',
 'NN',
 'SC',
 'RB',
 'JJ',
 'IN',
 'NNP',
 'SC',
 'VB',
 'CD',
 'NN',
 'PRP',
 'Z',
 'RB',
 'VB',
 'CD',
 'NN',
 'IN',
 'NNP',
 'SC',
 'MD',
 'VB',
 'NN',
 'IN',
 'NN',
 'PR',
 'Z',
 'SC',
 'SC',
 'PRP',
 'PRP',
 'VB',
 'NN',
 'PR',
 'NN',
 'MD',
 'VB',
 'IN',
 'NN',
 'IN',
 'NNP',
 'NNP',
 'Z',
 'NNP',
 'PR',
 'RB',
 'SC',
 'IN',
 'NNP',
 'Z',
 'SC',
 'RB',
 'IN',
 'NNP',
 'NEG',
 'JJ',
 'WH',
 'NN',
 'PRP',
 'Z',
 'NNP',
 'NNP',
 'NNP',
 'VB',
 'NNP',
 'Z',
 'JJ',
 'IN',
 'CD',
 'IN',
 'CD',
 'NN',
 'NNP',
 'NNP',
 'Z',
 'NNP',
 'NNP',
 'NNP',
 'NNP',
 'JJ',
 'Z',
 'JJ',
 'Z',
 'VB',
 'Z',
 'NN',
 'Z',
 'CC',
 'NN',
 'SC',
 'VB',
 'NN',
 'NN',
 'SC',
 'JJ',
 'Z',
 'NNP',
 'NNP',
 'NNP',
 'Z',
 'NNP',
 'VB',
 'NN',
 'NN',
 'IN',
 'NN',
 'NNP',
 'NNP',
 'NNP',
 'IN',
 'NN',
 'PR',
 'Z',
 'NNP',
 'VB',
 'IN',
 'NNP',
 'NNP',
 'CC',
 'NNP',
 'NNP',
 'NN',
 'MD',
 'VB',
 'NNP',
 'IN',
 'NNP',
 'NNP',
 'Z',
 'NNP',
 'NN',
 'VB',
 'NN',
 'VB',
 'IN',
 'NNP',
 'Z',
 'DT',
 'NN',
 'IN',
 'NNP',
 'NNP',
 'VB',
 'NN',
 'SC',
 'NEG',
 'VB',
 'NN',
 'Z',
 'NNP',
 'RB',
 'VB',
 'NN',
 'RB',
 'IN',
 'NN',
 'Z',
 'NEG',
 'VB',
 'IN',
 'NNP',
 'NNP',
 'Z',
 'NN',
 'NN',
 'RB',
 'VB',
 'JJ',
 'IN',
 'NNP',
 'NNP',
 'Z']

In [116]:
list_new_kata = [k[0] for k in new_testing[0]]

In [117]:
list_new_kata

[u'Jenis',
 u'monyet',
 u'yang',
 u'dikerahkan',
 u'pemkot',
 u'berbadan',
 u'besar',
 u',',
 u'berekor',
 u'panjang',
 u',',
 u'dan',
 u'memiliki',
 u'wajah',
 u'berwarna',
 u'hitam',
 u'.',
 u'Kedua',
 u'orang',
 u'terkaya',
 u'dunia',
 u'itu',
 u'sudah',
 u'berhasil',
 u'membujuk',
 u'banyak',
 u'orang',
 u'yang',
 u'sangat',
 u'kaya',
 u'di',
 u'Amerika',
 u'agar',
 u'menyumbangkan',
 u'separuh',
 u'kekayaan',
 u'mereka',
 u'.',
 u'Hanya',
 u'butuh',
 u'enam',
 u'tahun',
 u'bagi',
 u'Zuckerberg',
 u'untuk',
 u'bisa',
 u'mencapai',
 u'kesuksesan',
 u'seperti',
 u'sekarang',
 u'ini',
 u',',
 u'setelah',
 u'sebelum',
 u'-nya',
 u'dia',
 u'meluncurkan',
 u'situs',
 u'ini',
 u'saat',
 u'masih',
 u'duduk',
 u'sebagai',
 u'mahasiswa',
 u'di',
 u'Universitas',
 u'Harvard',
 u'.',
 u'Jamrud',
 u'itu',
 u'akhirnya',
 u'sampai',
 u'ke',
 u'Amerika',
 u',',
 u'meskipun',
 u'setibanya',
 u'di',
 u'Amerika',
 u'tidak',
 u'jelas',
 u'siapa',
 u'pemilik',
 u'-nya',
 u'.',
 u'Sejumlah',
 u'surat kabar',
 u'Brasil',
 u'melaporkan',
 u'Tiririca',
 u'-',
 u'sama',
 u'seperti',
 u'satu',
 u'dari',
 u'sepuluh',
 u'warga',
 u'Brasil',
 u'buta aksara',
 u'.',
 u'Universitas',
 u'Indonesia ',
 u'adalah ',
 u'kampus ',
 u'modern',
 u',',
 u'komprehensif',
 u',',
 u'terbuka',
 u',',
 u'multibudaya',
 u',',
 u'dan',
 u'humanis',
 u'yang',
 u'mencakup',
 u'disiplin',
 u'ilmu',
 u'yang',
 u'luas',
 u'.',
 u'Di',
 u'Korea',
 u'Selatan',
 u',',
 u'Wings',
 u'menjadi',
 u'album',
 u'terlaris',
 u'di',
 u'sejarah',
 u'Gaon',
 u'Album',
 u'Chart',
 u'pada',
 u'waktu',
 u'itu',
 u'.',
 u'Google',
 u'didirikan',
 u'oleh',
 u'Larry',
 u'Page',
 u'dan',
 u'Sergey',
 u'Brin',
 u'saat',
 u'masih',
 u'mahasiswa',
 u'Ph.D.',
 u'di',
 u'Universitas',
 u'Stanford',
 u'.',
 u'Berhubung',
 u'monyet',
 u'adalah',
 u'satwa',
 u'dilindungi',
 u'di',
 u'India',
 u',',
 u'para',
 u'penjaga',
 u'di',
 u'Taj',
 u'Mahal',
 u'membuat',
 u'penanganan',
 u'agar',
 u'tidak',
 u'mengganggu',
 u'pengunjung',
 u'.',
 u'Salah',
 u'satunya',
 u'adalah',
 u'menakut',
 u'nakutinya',
 u'dengan',
 u'ketapel',
 u'.',
 u'Tak',
 u'cuma',
 u'di',
 u'Taj',
 u'Mahal',
 u',',
 u'kawanan',
 u'monyet',
 u'juga',
 u'mulai',
 u'agresif',
 u'di',
 u'New',
 u'Delhi',
 u'.']

In [118]:
new_test = pd.DataFrame({'kata': list_new_kata, 'tag': list_new_tag})

In [119]:
new_test

           kata  tag
0         Jenis   NN
1        monyet   NN
2          yang   SC
3    dikerahkan   VB
4        pemkot   VB
5      berbadan   NN
6         besar   JJ
7             ,    Z
8       berekor   NN
9       panjang   JJ
10            ,    Z
11          dan   CC
12     memiliki   VB
13        wajah   NN
14     berwarna   NN
15        hitam   JJ
16            .    Z
17        Kedua   CD
18        orang   NN
19      terkaya   NN
20        dunia   NN
21          itu   PR
22        sudah   MD
23     berhasil   VB
24     membujuk   VB
25       banyak   CD
26        orang   NN
27         yang   SC
28       sangat   RB
29         kaya   JJ
..          ...  ...
167     membuat   VB
168  penanganan   NN
169        agar   SC
170       tidak  NEG
171  mengganggu   VB
172  pengunjung   NN
173           .    Z
174       Salah  NNP
175     satunya   RB
176      adalah   VB
177     menakut   NN
178   nakutinya   RB
179      dengan   IN
180     ketapel   NN
181           .    Z
182         Tak  NEG
183        cuma   VB
184          di   IN
185         Taj  NNP
186       Mahal  NNP
187           ,    Z
188     kawanan   NN
189      monyet   NN
190        juga   RB
191       mulai   VB
192     agresif   JJ
193          di   IN
194         New  NNP
195       Delhi  NNP
196           .    Z

[197 rows x 2 columns]

In [120]:
new_test.to_csv('list_new_test.csv', index=False)